"""
Merchant Analytics router — summary metrics, deterministic opportunity engine generation, and Task 13 Revenue Agent analysis endpoints.
Enforces strict merchant data isolation: merchants can only access their own data.
Customers are denied access (HTTP 403).
"""

import logging
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, status

from app.agents import revenue_agent
from app.core.database import db_manager
from app.core.dependencies import require_merchant
from app.schemas.analytics import AnalyticsSummaryResponse, RevenueOpportunitiesResponse
from app.schemas.audit import AuditAction, AuditResourceType
from app.schemas.opportunity import (
    BulkOpportunityAnalysisResponse,
    OpportunityQueryResponse,
    RevenueOpportunityAnalysisResponse,
    RevenueOpportunityRecord,
)
from app.services import opportunity_engine, opportunity_service
from app.services.audit_service import record_audit_event

logger = logging.getLogger("razorreach.analytics_router")

router = APIRouter(prefix="/merchants", tags=["Merchant Analytics"])


async def _get_authenticated_merchant_id(db, current_user: dict) -> str:
    """Helper to verify user owns a valid merchant profile and return merchant_id."""
    if db is None:
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="Database service unavailable")

    merchant = await db.merchants.find_one({"user_id": current_user["id"]})
    if not merchant:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Merchant profile not found")

    return str(merchant["_id"])


@router.get("/analytics/summary", response_model=AnalyticsSummaryResponse)
async def get_merchant_summary(
    period_days: int = Query(30, ge=1, le=365, description="Period in days (default 30)"),
    current_user: dict = Depends(require_merchant),
):
    """
    Get aggregated analytics summary metrics for the authenticated merchant over the given period.
    Strictly isolated to the merchant's own data.
    """
    db = db_manager.get_db()
    merchant_id = await _get_authenticated_merchant_id(db, current_user)
    return await opportunity_service.get_merchant_analytics_summary(
        db=db,
        merchant_id=merchant_id,
        period_days=period_days,
    )


@router.get("/opportunities", response_model=RevenueOpportunitiesResponse)
async def get_merchant_opportunities(
    period_days: int = Query(30, ge=1, le=365, description="Period in days (default 30)"),
    current_user: dict = Depends(require_merchant),
):
    """
    Get evidence-backed revenue opportunities generated by backend aggregations and AI formatting.
    Strictly isolated to the merchant's own products and demand.
    """
    db = db_manager.get_db()
    merchant_id = await _get_authenticated_merchant_id(db, current_user)
    return await revenue_agent.generate_merchant_opportunities(
        db=db,
        merchant_id=merchant_id,
        period_days=period_days,
    )


@router.post("/opportunities/generate", response_model=OpportunityQueryResponse)
async def generate_merchant_opportunities_deterministic(
    period_days: int = Query(30, ge=1, le=365, description="Period in days (default 30)"),
    current_user: dict = Depends(require_merchant),
):
    """
    Run 100% deterministic Revenue Opportunity Engine without AI processing.
    Aggregates analytics events, computes scores & priorities, and persists structured candidate records.
    Strictly isolated to authenticated merchant.
    """
    db = db_manager.get_db()
    merchant_id = await _get_authenticated_merchant_id(db, current_user)
    records = await opportunity_engine.generate_and_persist_opportunities(
        db=db,
        merchant_id=merchant_id,
        period_days=period_days,
    )

    await record_audit_event(
        db=db,
        action=AuditAction.OPPORTUNITY_GENERATED,
        resource_type=AuditResourceType.OPPORTUNITY,
        actor_id=current_user["id"],
        actor_role="merchant",
        metadata={"count": len(records), "period_days": period_days},
    )

    return OpportunityQueryResponse(
        merchant_id=merchant_id,
        total_count=len(records),
        opportunities=records,
    )


@router.post("/opportunities/{opportunity_id}/analyze", response_model=RevenueOpportunityAnalysisResponse)
async def analyze_single_opportunity_endpoint(
    opportunity_id: str,
    current_user: dict = Depends(require_merchant),
):
    """
    Task 13 Endpoint: Request AI analysis for a specific revenue opportunity owned by authenticated merchant.
    Gemini generates natural language business interpretation and suggested actions.
    Authoritative backend metric evidence remains 100% untouched.
    """
    db = db_manager.get_db()
    merchant_id = await _get_authenticated_merchant_id(db, current_user)

    opp_doc = await db.revenue_opportunities.find_one({"_id": opportunity_id})
    if not opp_doc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Opportunity not found")

    if opp_doc.get("merchant_id") != merchant_id:
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Access to opportunity denied")

    if "_id" in opp_doc and "id" not in opp_doc:
        opp_doc["id"] = str(opp_doc["_id"])

    opportunity_record = RevenueOpportunityRecord(**opp_doc)
    res = await revenue_agent.analyze_single_opportunity(opportunity_record)

    try:
        await db.revenue_opportunities.update_one(
            {"_id": opportunity_id},
            {"$set": {"analysis": res.analysis.model_dump(), "status": "reviewed"}},
        )
    except Exception as e:
        logger.warning(f"Failed to persist analysis to opportunity {opportunity_id}: {e}")

    await record_audit_event(
        db=db,
        action=AuditAction.OPPORTUNITY_ANALYZED,
        resource_type=AuditResourceType.OPPORTUNITY,
        actor_id=current_user["id"],
        actor_role="merchant",
        resource_id=opportunity_id,
        metadata={"opportunity_type": opportunity_record.type.value, "score": opportunity_record.score},
    )

    await record_audit_event(
        db=db,
        action=AuditAction.REVENUE_AGENT_USED,
        resource_type=AuditResourceType.AI_AGENT,
        actor_id=current_user["id"],
        actor_role="merchant",
        resource_id=opportunity_id,
    )

    return res


@router.post("/opportunities/analyze", response_model=BulkOpportunityAnalysisResponse)
async def analyze_bulk_opportunities_endpoint(
    limit: int = Query(5, ge=1, le=10, description="Max opportunities to analyze (limit 10)"),
    current_user: dict = Depends(require_merchant),
):
    """
    Task 13 Endpoint: Perform bulk AI analysis on current revenue opportunities owned by authenticated merchant.
    Bounded to maximum 10 opportunities per call.
    """
    db = db_manager.get_db()
    merchant_id = await _get_authenticated_merchant_id(db, current_user)

    records = await opportunity_engine.get_merchant_opportunities(
        db=db,
        merchant_id=merchant_id,
        limit=limit,
    )

    res = await revenue_agent.analyze_bulk_opportunities(records, max_limit=limit)

    for item in res.results:
        try:
            await db.revenue_opportunities.update_one(
                {"_id": item.opportunity.id},
                {"$set": {"analysis": item.analysis.model_dump(), "status": "reviewed"}},
            )
        except Exception as e:
            logger.warning(f"Failed to persist bulk analysis to {item.opportunity.id}: {e}")

    await record_audit_event(
        db=db,
        action=AuditAction.REVENUE_AGENT_USED,
        resource_type=AuditResourceType.AI_AGENT,
        actor_id=current_user["id"],
        actor_role="merchant",
        metadata={"bulk_analyzed": res.total_analyzed},
    )

    return res

