from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class OpportunityType(str, Enum):
    UNSERVED_DEMAND = "unserved_demand"
    LOW_CONVERSION = "low_conversion"
    CART_ABANDONMENT = "cart_abandonment"
    STOCK_GAP = "stock_gap"
    HIGH_DEMAND_CATEGORY = "high_demand_category"


class OpportunityPriority(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class OpportunityStatus(str, Enum):
    NEW = "new"
    REVIEWED = "reviewed"
    DISMISSED = "dismissed"
    ACTIONED = "actioned"


class OpportunityEvidence(BaseModel):
    search_count: Optional[int] = None
    zero_result_count: Optional[int] = None
    zero_result_rate: Optional[float] = None
    view_count: Optional[int] = None
    cart_add_count: Optional[int] = None
    purchase_count: Optional[int] = None
    conversion_rate: Optional[float] = None
    abandonment_rate: Optional[float] = None
    current_stock: Optional[int] = None
    period_days: int = 30


# ===== Task 13 AI Agent Schemas =====

class RevenueAgentAnalysis(BaseModel):
    title: str = Field(..., description="Grounded analysis title")
    summary: str = Field(..., description="Executive summary grounded strictly in evidence")
    evidence_summary: List[str] = Field(default_factory=list, description="Bullet list of factual evidence items")
    interpretation: str = Field(..., description="Business interpretation explaining potential hypotheses")
    suggested_action: str = Field(..., description="Recommended merchant action for consideration")
    confidence: str = Field("high", description="Confidence level based on sample size and signal quality (high, medium, low)")


class RevenueOpportunityRecord(BaseModel):
    id: str
    merchant_id: str
    type: OpportunityType
    target: str = Field(..., description="Target keyword, product ID, or category name")
    score: float = Field(..., ge=0.0, le=1.0, description="Heuristic opportunity score from 0.0 to 1.0")
    priority: OpportunityPriority
    status: OpportunityStatus = OpportunityStatus.NEW
    title: str
    summary: str
    evidence: OpportunityEvidence
    suggested_action: str
    estimated_potential_revenue: Optional[float] = Field(None, description="Estimated potential revenue (never guaranteed)")
    period_start: str
    period_end: str
    generated_at: str
    analysis: Optional[RevenueAgentAnalysis] = Field(None, description="Optional AI interpretation generated by Revenue Agent")


class OpportunityQueryResponse(BaseModel):
    merchant_id: str
    total_count: int
    opportunities: List[RevenueOpportunityRecord] = Field(default_factory=list)


class RevenueOpportunityAnalysisResponse(BaseModel):
    opportunity: RevenueOpportunityRecord = Field(..., description="Authoritative Task 12 opportunity record (untouched evidence)")
    analysis: RevenueAgentAnalysis = Field(..., description="AI interpretation generated by Revenue Agent")


class BulkOpportunityAnalysisResponse(BaseModel):
    merchant_id: str
    total_analyzed: int
    results: List[RevenueOpportunityAnalysisResponse] = Field(default_factory=list)
